### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by FergusonAJ** [alife-data-standards/alife-data-standards#14]
How should versioning work in the data standard? 
Early discussions lead to two ideas: 
1. One semantic version number for the entire data standard
2. Separate semantic version numbers for each standard (phylogeny, genome, etc.)

So far the consensus seems to be that one semantic version number for the whole standard would work well. Of course, discussion is welcome!

**Comment by FergusonAJ** [comment]
Cliff had a great idea! If we used one version number for the entire standard, the main page should list when each standard was last changed. 
Example:
 Phylogeny  -> Last changed version x.y.z. (Maybe include a date, too?)

**Comment by emilydolson** [comment]
This is a great idea! I have added it to the readme.
