### ISSUE TITLE
Should special values by negative integers or strings?

### ISSUE THREAD

**Issue by emilydolson** [alife-data-standards/alife-data-standards#6]
A topic that we discussed at the workshop at ALife but did not resolve is how to specify special values in the id field for phylogenies. The two options we discussed with negative integers and strings. In either case, we would come up with a convention for how to indicate common special values (the two main ones being "no ancestor", and "ancestor that exists outside this experiment").

The main benefit of strings is that they're clearer and reduce the risk of introducing bugs. The main benefit of numbers is that many data processing scripts are easier to write if we know for sure that the field will always be numeric.

**Comment by thefalconpen** [comment]
I would personally prefer strings as the always numeric limiter is nice. However I'm sort of also inclined to say that I would probably use strings in my actual work but a dedicated conversion function so I don't have to allow strings internally but can use them for better interaction. Not sure how that sort of usage would fit with the standard.

**Comment by amlalejini** [comment]
As the phylogeny standard is currently defined, IDs are non-negative integers. A 'no_parent' ID would be illegal. I.e., I tend to agree with Cliff that we shouldn't require a line with the 'no_parent' ID. 

I agree with Penny, I would personally prefer strings. They can be much more descriptive in their meaning within the data file.

**Comment by thefalconpen** [comment]
Perhaps a mid point would be to make it numeric with a standard string
label. So the standard is the negative number but the standard label if you
translate to string.

**Comment by emilydolson** [comment]
I like that idea but the problem is we still have to choose something for people to write in the actual file. If we say it's ever okay to use strings, we lose the data manipulation benefits. That said, I'm increasingly leaning towards strings. They make it harder to have undiscovered bugs, and that's a good thing to build into a standard.

I totally agree that special values should be an exception to the "must correspond to a row in the file" rule for ancestor lists.

**Comment by emilydolson** [comment]
Sounds like we're all the same page with regard to using strings and allowing special values.

Cliff notes that we should be careful to specify that values with special meaning only hold that meaning within the relevant column (e.g. "none" in ancestor_list means something different than "none" in a different column).
