### ISSUE TITLE
How should we handle numbers that may need a range of precision?

### ISSUE THREAD

**Issue by emilydolson** [alife-data-standards/alife-data-standards#7]
Another topic that came up at ALife but was not fully resolved is how we should handle numbers that could either be floating point or large integers.

Options we discussed:
- Represent the number as a string that's as long as it needs to be
- Allow all numeric fields to have optional paired "scale" fields (e.g. `originTime_scale`) which are multipliers to apply to the number in the corresponding field.

**Comment by amlalejini** [comment]
I like representing numbers as strings that can be as long as necessary, but I also don't work with things where numbers get to be so huge that file size becomes an issue. And without a description of how huge a number is (or how much precision it requires to describe), I can see tools written in languages like C++ silently overflowing and giving bad/misleading output.

Would be good to hear from someone who's been forced to wrestle with this sort of issue a lot in their work; how do you handle it?

**Comment by emilydolson** [comment]
Unless there are further objections, it sounds like writing all numbers as strings is our best option. It does mean tool-writers have to be careful with validation, to ensure that tools aren't attempting to read in numbers that they can't represent. We can provide validators to help with this problem.
